"/ur5/controller_manager":
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController


"/ur5/speed_scaling_state_broadcaster":
  ros__parameters:
    state_publish_rate: 100.0

"/ur5/joint_trajectory_controller":
  ros__parameters:
    joints:
      - $ur5_shoulder_pan_joint
      - $ur5_shoulder_lift_joint
      - $ur5_shoulder_lift_joint
      - $ur5_wrist_1_joint
      - $ur5_wrist_2_joint
      - $ur5_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

"/ur5/scaled_joint_trajectory_controller":
  ros__parameters:
    joints:
      - $ur5_shoulder_pan_joint
      - $ur5_shoulder_lift_joint
      - $ur5_elbow_joint
      - $ur5_wrist_1_joint
      - $ur5_wrist_2_joint
      - $ur5_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

"/ur5/forward_velocity_controller":
  ros__parameters:
    joints:
      - $ur5_shoulder_pan_joint
      - $ur5_shoulder_lift_joint
      - $ur5_elbow_joint
      - $ur5_wrist_1_joint
      - $ur5_wrist_2_joint
      - $ur5_wrist_3_joint
    interface_name: velocity

"/ur5/forward_position_controller":
  ros__parameters:
    joints:
      - $ur5_shoulder_pan_joint
      - $ur5_shoulder_lift_joint
      - $ur5_elbow_joint
      - $ur5_wrist_1_joint
      - $ur5_wrist_2_joint
      - $ur5_wrist_3_joint
